fragment PostParts on Post {
  __typename
  title
  date
  author
  excerpt
  heroImage
  body
}

fragment SiteContentParts on SiteContent {
  __typename
  heroTagline
  heroSubtitle
  heroDescription
  heroVideoUrl
  heroFallbackImage
  stats {
    __typename
    number
    label
  }
  storyParagraph1
  storyParagraph2
  storyParagraph3
  timelineItems {
    __typename
    label
    date
    desc
  }
  blockquoteText
  blockquoteCitation
  whyNowTagline
  whyNowHeading
  whyNowParagraph1
  whyNowParagraph2
  whyNowParagraph3
  filmmakers {
    __typename
    photo
    name
    title
    bio
    email
  }
  contactTagline
  contactHeading
  contactDescription
  donateTagline
  donateHeading
  donateHeadingItalic
  donateDescription
  tiers {
    __typename
    id
    name
    amount
    description
  }
}
